AllCops:
  DisplayCopNames: true
  UseCache: true
  CacheRootDirectory: ./tmp
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 80

Style/Lambda:
  EnforcedStyle: lambda

Style/WordArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - Rakefile

Metrics/MethodLength:
  Exclude:
    - Rakefile

Bundler/OrderedGems:
  Enabled: false
