name: Bug report
description: Report an issue with Lintje.
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us how you called Lintje, what happened and what you expected to happen.
      value: |
        ## What happened?

        _Describe what Lintje did._

        How I called the Lintje command:
        ```sh
        $ lintje ...
        ```

        The output I received:
        ```
        Lintje output...
        ```

        ## What was supposed to happen?

        Describe what Lintje should have done instead.
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of Lintje are you running? Enter the output of `lintje --version`, GitHub Action version or Docker image version.
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: What Operating System are you seeing the problem on?
      multiple: true
      options:
        - macOS
        - Linux distribution
        - Alpine Linux
        - Microsoft Windows
    validations:
      required: true
  - type: dropdown
    id: execution
    attributes:
      label: How are you running Lintje?
      multiple: true
      options:
        - Directly on host machine (Default)
        - Docker container (official tombruijn/lintje image)
        - Docker container (other/custom container)
        - GitHub Action
    validations:
      required: true
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://lintje.dev/code-of-conduct/).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
