#!/bin/bash

set -eu

which cross > /dev/null 2>&1 || cargo install cross

rm -rf dist
mkdir -p dist
build_for() {
    builder="$1"
    target="$2"
    filename="$3"
    echo "Building $target ($filename)"
    rm -rf dist/$target
    mkdir -p dist/$target
    rustup target add $target
    $builder build --release --target $target
    cp target/$target/release/$filename dist/$target/
}

echo
build_for cargo x86_64-apple-darwin lintje
echo
build_for cargo aarch64-apple-darwin lintje
echo
build_for cross x86_64-unknown-linux-gnu lintje
echo
build_for cross aarch64-unknown-linux-gnu lintje
echo
build_for cross x86_64-unknown-linux-musl lintje
echo
build_for cross aarch64-unknown-linux-musl lintje
echo
build_for cross x86_64-pc-windows-gnu lintje.exe
